export class Cas {
  _id: string = "";
  ucenik: string = "";
  nastavnik: string = "";
  predmet: string = "";
  datum_vreme_start: string = "";
  datum_vreme_kraj: string = "";
  kratak_opis: string = "";
  dupli_cas: boolean = false;
  trajanje: number = 0;
  status: string = "";
  tekst: string = "";
  ocena_ucenik: number = 0;
  komentar_ucenik: string = "";
  ocena_nastavnik: number = 0;
  komentar_nastavnik: string = "";
  nIme: string = "";
  nPrezime: string = "";
  uIme: string = "";
  uPrezime: string = "";
  uBrOcena: number = 0;
  uProsecnaOcena: number = 0;
  ucionicaDisabled: boolean = true;
  otkazivanjeDisabled: boolean = true;
}
