export class Korisnik {
  kor_ime: string = "";
  lozinka: string = "";
  tip: string = "";
  bezb_pitanje: string = "";
  bezb_odgovor: string = "";
  ime: string = "";
  prezime: string = "";
  pol: string = "";
  adresa: string = "";
  telefon: string = "";
  email: string = "";
  prof_slika: string = "";
  zahtev_status: string = "";
  tip_skole: string = "";
  tr_razred: number = 0;
  cv_pdf: string = "";
  predmeti: string[] = [];
  uzrast: string[] = [];
  culi_sajt: string = "";
  dostupnost: string[] = [];
  ocena: number = 0;
  br_ocena: number = 0;
}
